version: '3.6'

services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: recommerce-php
        depends_on:
          - database
        volumes:
            - './api:/var/www/html:cached'

    nginx:
        image: 'nginx:1.13.6'
        container_name: recommerce-nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './api:/var/www/html:cached'
            - './config/nginx:/etc/nginx/conf.d:cached'

    database:
        image: 'mariadb:10.5'
        container_name: recommerce-database
        restart: 'on-failure'
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root

networks: 
  default:
    name: recommerce